# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b419143ddb8c755a2a8b28ac6f3568f71c91e5a735b17283b62bc20df94ada22dfea30b7cc7117db3ab9896f691e56896316560a29966125624c164e9514267

test:
  secret_key_base: 9caf6273632b05a513374dff5cd938b06186e205e16d1788598c7533b058a3716970066caece04e42f39dd3cd121acaf743cdb5bc75e778e17d26c6011a4a483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
